export interface Recipe {
  id: string
  title: string
  description: string
  image: string
  category: string
  cookTime: string
  servings: number
  difficulty: "Easy" | "Medium" | "Hard"
  rating: number
  reviews: number
  author: string
  authorAvatar: string
  bookmarked: boolean
  ingredients: string[]
  steps: string[]
  createdAt: string
}

export const categories = [
  "All",
  "Pasta",
  "Bread",
  "Breakfast",
  "Seafood",
  "Pizza",
  "Dessert",
  "Salad",
  "Soup",
  "Vegan",
]

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Tuscan Herb Pasta",
    description:
      "A rich and creamy pasta dish with fresh basil, sun-dried tomatoes, and a hint of garlic. Perfect for a cozy dinner.",
    image: "/images/recipes/1.jpg",
    category: "Pasta",
    cookTime: "30 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.8,
    reviews: 124,
    author: "Chef Maria",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "400g penne pasta",
      "2 cups fresh basil leaves",
      "1/2 cup sun-dried tomatoes",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1/2 cup parmesan cheese",
      "2 tbsp olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook pasta according to package directions until al dente. Reserve 1 cup pasta water before draining.",
      "In a large skillet, heat olive oil over medium heat. Add minced garlic and cook until fragrant, about 1 minute.",
      "Add sun-dried tomatoes and cook for 2 minutes, stirring occasionally.",
      "Pour in the heavy cream and bring to a gentle simmer. Cook for 3-4 minutes until slightly thickened.",
      "Add the cooked pasta to the sauce, tossing to combine. Add pasta water as needed for consistency.",
      "Stir in fresh basil and parmesan cheese. Season with salt and pepper. Serve immediately.",
    ],
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    title: "Artisan Sourdough Bread",
    description:
      "A classic sourdough with a perfectly crispy crust and soft, tangy interior. Worth every moment of patience.",
    image: "/images/recipes/2.jpg",
    category: "Bread",
    cookTime: "4 hrs",
    servings: 8,
    difficulty: "Hard",
    rating: 4.9,
    reviews: 89,
    author: "Baker Tom",
    authorAvatar: "",
    bookmarked: true,
    ingredients: [
      "500g bread flour",
      "350ml warm water",
      "100g sourdough starter",
      "10g sea salt",
      "Rice flour for dusting",
    ],
    steps: [
      "Mix flour, water, and sourdough starter in a large bowl. Let rest for 30 minutes (autolyse).",
      "Add salt and mix thoroughly. Perform stretch and folds every 30 minutes for 2 hours.",
      "Shape the dough into a tight ball and place in a floured banneton basket.",
      "Refrigerate overnight for 8-12 hours for a slow, cold fermentation.",
      "Preheat oven with a Dutch oven inside to 500F. Score the dough and bake covered for 20 minutes.",
      "Remove lid and bake for another 20-25 minutes until deep golden brown. Cool completely before slicing.",
    ],
    createdAt: "2026-01-20",
  },
  {
    id: "3",
    title: "Berry Bliss Smoothie Bowl",
    description:
      "A vibrant and nutritious smoothie bowl packed with antioxidants, topped with fresh fruits and crunchy granola.",
    image: "/images/recipes/3.jpg",
    category: "Breakfast",
    cookTime: "10 min",
    servings: 1,
    difficulty: "Easy",
    rating: 4.7,
    reviews: 203,
    author: "Wellness Wren",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "1 cup frozen acai puree",
      "1 banana, frozen",
      "1/2 cup mixed berries",
      "1/4 cup almond milk",
      "Toppings: granola, coconut flakes, sliced banana, fresh berries",
    ],
    steps: [
      "Blend acai puree, frozen banana, mixed berries, and almond milk until thick and smooth.",
      "Pour into a bowl and arrange your toppings in rows across the top.",
      "Serve immediately and enjoy the vibrant flavors.",
    ],
    createdAt: "2026-02-01",
  },
  {
    id: "4",
    title: "Honey Glazed Salmon",
    description:
      "Perfectly seared salmon with a sweet honey glaze, served with roasted vegetables and a squeeze of fresh lemon.",
    image: "/images/recipes/4.jpg",
    category: "Seafood",
    cookTime: "25 min",
    servings: 2,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 156,
    author: "Chef Maria",
    authorAvatar: "",
    bookmarked: true,
    ingredients: [
      "2 salmon fillets (6oz each)",
      "3 tbsp honey",
      "2 tbsp soy sauce",
      "1 tbsp Dijon mustard",
      "2 cloves garlic, minced",
      "1 lemon, juiced",
      "Fresh herbs for garnish",
    ],
    steps: [
      "Pat salmon fillets dry and season with salt and pepper.",
      "Mix honey, soy sauce, Dijon mustard, garlic, and lemon juice in a small bowl.",
      "Heat an oven-safe skillet over medium-high heat with olive oil. Sear salmon skin-side up for 3 minutes.",
      "Flip salmon and pour the honey glaze over the top.",
      "Transfer to a 400F oven and bake for 8-10 minutes until cooked through.",
      "Garnish with fresh herbs and lemon slices. Serve with roasted vegetables.",
    ],
    createdAt: "2026-02-05",
  },
  {
    id: "5",
    title: "Neapolitan Margherita Pizza",
    description:
      "An authentic wood-fired style pizza with San Marzano tomatoes, fresh mozzarella, and aromatic basil.",
    image: "/images/recipes/5.jpg",
    category: "Pizza",
    cookTime: "1 hr",
    servings: 4,
    difficulty: "Medium",
    rating: 4.8,
    reviews: 178,
    author: "Baker Tom",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "500g tipo 00 flour",
      "325ml warm water",
      "7g active dry yeast",
      "1 tsp sugar",
      "10g salt",
      "San Marzano tomatoes",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "Extra virgin olive oil",
    ],
    steps: [
      "Dissolve yeast and sugar in warm water. Let sit for 5 minutes until foamy.",
      "Mix flour and salt, then add yeast mixture. Knead for 10 minutes until smooth and elastic.",
      "Let dough rise in a covered bowl for 1 hour until doubled in size.",
      "Divide into 4 balls. Stretch each into a thin round on a floured surface.",
      "Top with crushed San Marzano tomatoes, torn mozzarella, and a drizzle of olive oil.",
      "Bake at the highest oven temperature (500F+) for 8-10 minutes. Add fresh basil after baking.",
    ],
    createdAt: "2026-02-10",
  },
  {
    id: "6",
    title: "Molten Chocolate Lava Cake",
    description:
      "An indulgent chocolate dessert with a warm, gooey center that flows like lava. A true showstopper.",
    image: "/images/recipes/6.jpg",
    category: "Dessert",
    cookTime: "20 min",
    servings: 4,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 312,
    author: "Pastry Chef Lina",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "200g dark chocolate (70%)",
      "150g unsalted butter",
      "3 large eggs",
      "3 egg yolks",
      "100g sugar",
      "50g all-purpose flour",
      "Cocoa powder for dusting",
      "Raspberry coulis for serving",
    ],
    steps: [
      "Preheat oven to 425F. Butter and dust 4 ramekins with cocoa powder.",
      "Melt chocolate and butter together in a double boiler, stirring until smooth.",
      "In a separate bowl, whisk eggs, egg yolks, and sugar until thick and pale.",
      "Fold the chocolate mixture into the egg mixture. Gently fold in the flour.",
      "Divide batter among the prepared ramekins. Bake for exactly 12-14 minutes.",
      "Let cool for 1 minute, then invert onto plates. Dust with powdered sugar and serve with raspberry coulis.",
    ],
    createdAt: "2026-02-15",
  },

  {
    id: "7",
    title: "Quinoa Harvest Salad",
    description: "A hearty and healthy salad featuring tri-color quinoa, roasted sweet potatoes, kale, and a zesty lemon-tahini dressing.",
    image: "/images/recipes/7.jpg",
    category: "Salad",
    cookTime: "40 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.6,
    reviews: 87,
    author: "Wellness Wren",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "1 cup tri-color quinoa",
      "2 large sweet potatoes, cubed",
      "1 bunch kale, chopped",
      "1/2 cup dried cranberries",
      "1/4 cup pumpkin seeds",
      "3 tbsp tahini",
      "1 lemon, juiced",
      "1 tbsp maple syrup"
    ],
    steps: [
      "Preheat oven to 400F. Toss sweet potato cubes with olive oil and roast for 25-30 minutes.",
      "Rinse and cook quinoa according to package directions.",
      "In a large bowl, massage kale with a little olive oil until tender.",
      "Whisk together tahini, lemon juice, maple syrup, and a splash of water for the dressing.",
      "Combine quinoa, roasted sweet potatoes, kale, cranberries, and pumpkin seeds.",
      "Drizzle with dressing and toss to combine. Serve warm or cold."
    ],
    createdAt: "2026-03-01"
  },
  {
    id: "8",
    title: "Thai Green Curry",
    description: "A fragrant and spicy authentic Thai green curry with coconut milk, bamboo shoots, and fresh Thai basil.",
    image: "/images/recipes/8.jpg",
    category: "Soup",
    cookTime: "30 min",
    servings: 4,
    difficulty: "Medium",
    rating: 4.8,
    reviews: 142,
    author: "Chef Maria",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "400ml coconut milk",
      "3 tbsp green curry paste",
      "500g chicken or tofu, cubed",
      "1 cup bamboo shoots",
      "1 cup green beans",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar",
      "Handful of Thai basil"
    ],
    steps: [
      "Heat a large pot over medium heat. Add a splash of coconut milk and the curry paste, fry until fragrant.",
      "Add the chicken or tofu and stir to coat in the paste.",
      "Pour in the remaining coconut milk and bring to a simmer.",
      "Add bamboo shoots and green beans. Cook for 10-15 minutes until vegetables are tender.",
      "Season with fish sauce and palm sugar.",
      "Stir in Thai basil leaves just before serving with jasmine rice."
    ],
    createdAt: "2026-03-10"
  },
  {
    id: "9",
    title: "Classic Margherita Pizza",
    description: "The quintessential Italian pizza with a thin crust, San Marzano tomatoes, fresh mozzarella, and aromatic basil.",
    image: "/images/recipes/9.jpg",
    category: "Pizza",
    cookTime: "15 min",
    servings: 2,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 215,
    author: "Baker Tom",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "Pizza dough ball",
      "1/2 cup San Marzano tomato sauce",
      "125g fresh mozzarella",
      "Fresh basil leaves",
      "Extra virgin olive oil",
      "Sea salt"
    ],
    steps: [
      "Preheat your oven and pizza stone to its highest setting (500F+).",
      "Stretch the dough into a 12-inch round on a floured surface.",
      "Spread tomato sauce evenly, leaving a border for the crust.",
      "Tear mozzarella into chunks and distribute over the sauce.",
      "Bake for 7-10 minutes until the crust is charred and cheese is bubbly.",
      "Finish with fresh basil, a drizzle of olive oil, and sea salt."
    ],
    createdAt: "2026-03-15"
  },
  {
    id: "10",
    title: "Fluffy Blueberry Pancakes",
    description: "Extra fluffy buttermilk pancakes bursting with fresh blueberries. The ultimate weekend breakfast treat.",
    image: "/images/recipes/10.jpg",
    category: "Breakfast",
    cookTime: "20 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.7,
    reviews: 189,
    author: "Wellness Wren",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 cups all-purpose flour",
      "2 tsp baking powder",
      "1/2 tsp salt",
      "1.5 cups buttermilk",
      "2 large eggs",
      "1/4 cup melted butter",
      "1 cup fresh blueberries",
      "Maple syrup for serving"
    ],
    steps: [
      "Whisk together flour, baking powder, and salt in a large bowl.",
      "In another bowl, beat eggs then stir in buttermilk and melted butter.",
      "Combine wet and dry ingredients, stirring until just mixed (some lumps are okay).",
      "Heat a griddle over medium heat and lightly grease with butter.",
      "Pour 1/4 cup batter for each pancake, then sprinkle with blueberries.",
      "Flip when bubbles appear on the surface. Cook until golden brown on both sides."
    ],
    createdAt: "2026-03-20"
  },
  {
    id: "11",
    title: "Beef Burgundy (Boeuf Bourguignon)",
    description: "A classic French beef stew braised in red wine with pearl onions, mushrooms, and bacon.",
    image: "/images/recipes/11.jpg",
    category: "Soup",
    cookTime: "3 hrs",
    servings: 6,
    difficulty: "Hard",
    rating: 4.9,
    reviews: 94,
    author: "Chef Maria",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "1.5kg beef chuck, cubed",
      "750ml red wine (Burgundy or Pinot Noir)",
      "200g bacon lardons",
      "500g mushrooms, quartered",
      "20 pearl onions",
      "3 carrots, sliced",
      "2 cloves garlic, minced",
      "Fresh thyme and bay leaves"
    ],
    steps: [
      "Brown the bacon in a large Dutch oven, then remove and set aside.",
      "Sear the beef cubes in batches in the bacon fat until browned on all sides.",
      "Add garlic, carrots, and onions. Cook for 5 minutes.",
      "Return beef and bacon to the pot. Pour in the wine and enough beef stock to cover.",
      "Add herbs, cover, and simmer for 2.5 hours or until beef is tender.",
      "In the last 20 minutes, sauté mushrooms and add them to the stew. Serve with mashed potatoes."
    ],
    createdAt: "2026-04-05"
  },
  {
    id: "12",
    title: "Homemade Garlic Naan",
    description: "Soft, pillowy Indian flatbread brushed with garlic butter and fresh cilantro.",
    image: "/images/recipes/12.jpg",
    category: "Bread",
    cookTime: "1 hr",
    servings: 6,
    difficulty: "Medium",
    rating: 4.8,
    reviews: 167,
    author: "Baker Tom",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 cups all-purpose flour",
      "1 tsp yeast",
      "1 tsp sugar",
      "1/2 cup warm water",
      "1/4 cup plain yogurt",
      "2 tbsp olive oil",
      "3 cloves garlic, minced",
      "2 tbsp melted butter",
      "Fresh cilantro"
    ],
    steps: [
      "Dissolve yeast and sugar in warm water. Let sit for 5 minutes.",
      "Mix flour, yogurt, oil, and yeast mixture into a soft dough. Knead for 5 minutes.",
      "Let rise in a warm place for 1 hour.",
      "Divide into 6 balls and roll into ovals.",
      "Cook on a very hot cast-iron skillet for 1-2 minutes per side until charred and bubbled.",
      "Brush immediately with a mix of melted butter and minced garlic. Garnish with cilantro."
    ],
    createdAt: "2026-04-10"
  },
  {
    id: "13",
    title: "Vegan Chocolate Avocado Mousse",
    description: "A rich, velvety chocolate mousse made with ripe avocados for a healthy and decadent treat.",
    image: "/images/recipes/13.jpg",
    category: "Vegan",
    cookTime: "10 min",
    servings: 3,
    difficulty: "Easy",
    rating: 4.5,
    reviews: 58,
    author: "Wellness Wren",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 ripe avocados",
      "1/2 cup cocoa powder",
      "1/2 cup maple syrup",
      "1/3 cup almond milk",
      "2 tsp vanilla extract",
      "Pinch of salt"
    ],
    steps: [
      "Scoop the flesh of the avocados into a food processor or blender.",
      "Add cocoa powder, maple syrup, almond milk, vanilla, and salt.",
      "Blend until completely smooth and creamy.",
      "Adjust sweetness if necessary.",
      "Transfer to bowls and chill in the refrigerator for at least 30 minutes before serving."
    ],
    createdAt: "2026-04-12"
  }
  ,
  {
    id: "14",
    title: "Lemon Garlic Shrimp Linguine",
    description: "Quick and bright shrimp pasta with garlic, lemon, and parsley — perfect for weeknights.",
    image: "/images/recipes/14.jpg",
    category: "Pasta",
    cookTime: "25 min",
    servings: 2,
    difficulty: "Easy",
    rating: 4.7,
    reviews: 64,
    author: "Chef Luca",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "200g linguine",
      "200g shrimp, peeled",
      "3 cloves garlic, minced",
      "2 tbsp olive oil",
      "1 lemon, zested and juiced",
      "2 tbsp chopped parsley",
      "Salt and pepper",
    ],
    steps: [
      "Cook linguine until al dente and reserve 1/2 cup pasta water.",
      "Sauté garlic in olive oil until fragrant, add shrimp and cook until pink.",
      "Add lemon zest, juice, and a splash of pasta water. Toss with linguine and parsley.",
      "Season and serve immediately.",
    ],
    createdAt: "2026-04-15",
  },
  {
    id: "15",
    title: "Mediterranean Chickpea Salad",
    description: "A refreshing salad with chickpeas, cucumber, cherry tomatoes, olives, and a lemon-oregano dressing.",
    image: "/images/recipes/15.jpg",
    category: "Salad",
    cookTime: "15 min",
    servings: 4,
    difficulty: "Easy",
    rating: 4.5,
    reviews: 34,
    author: "Olivia Greens",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 cans chickpeas, drained",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 cup Kalamata olives, sliced",
      "1/4 cup red onion, thinly sliced",
      "2 tbsp olive oil",
      "Juice of 1 lemon",
      "1 tsp dried oregano",
      "Salt and pepper",
    ],
    steps: [
      "Combine chickpeas, cucumber, tomatoes, olives, and red onion in a bowl.",
      "Whisk olive oil, lemon juice, oregano, salt, and pepper. Pour over salad and toss.",
      "Chill briefly and serve.",
    ],
    createdAt: "2026-04-16",
  },
  {
    id: "16",
    title: "Coconut Lime Vegan Tacos",
    description: "Flavorful jackfruit tacos with coconut-lime slaw and a spicy crema — plant-based and delicious.",
    image: "/images/recipes/16.jpg",
    category: "Vegan",
    cookTime: "35 min",
    servings: 6,
    difficulty: "Medium",
    rating: 4.6,
    reviews: 21,
    author: "Green Kitchen",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 cans young jackfruit, drained",
      "1 can coconut milk",
      "1 tbsp curry powder",
      "8 small tortillas",
      "1/2 small cabbage, shredded",
      "Juice of 1 lime",
      "Salt and chili flakes",
    ],
    steps: [
      "Simmer jackfruit with coconut milk and curry powder until tender and shredded.",
      "Mix cabbage with lime juice and a pinch of salt for the slaw.",
      "Assemble tacos with jackfruit and slaw. Serve with extra lime.",
    ],
    createdAt: "2026-04-17",
  },
  {
    id: "17",
    title: "Salted Caramel Panna Cotta",
    description: "Silky panna cotta topped with a buttery salted caramel sauce.",
    image: "/images/recipes/17.jpg",
    category: "Dessert",
    cookTime: "4 hrs",
    servings: 4,
    difficulty: "Medium",
    rating: 4.9,
    reviews: 48,
    author: "Pastry Chef Lina",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 cups heavy cream",
      "1/2 cup sugar",
      "1 tsp vanilla",
      "2 tsp gelatin",
      "Salted caramel sauce",
    ],
    steps: [
      "Bloom gelatin in a little cold water.",
      "Heat cream, sugar, and vanilla until sugar dissolves. Whisk in gelatin.",
      "Pour into molds and chill until set. Top with salted caramel.",
    ],
    createdAt: "2026-04-18",
  },
  {
    id: "18",
    title: "Smoky Grilled Mackerel",
    description: "Simple grilled mackerel with a smoky char and lemon-herb finish.",
    image: "/images/recipes/18.jpg",
    category: "Seafood",
    cookTime: "20 min",
    servings: 2,
    difficulty: "Easy",
    rating: 4.6,
    reviews: 26,
    author: "Fisher Sam",
    authorAvatar: "",
    bookmarked: false,
    ingredients: [
      "2 whole mackerel, cleaned",
      "2 tbsp olive oil",
      "1 lemon",
      "Fresh dill",
      "Salt and pepper",
    ],
    steps: [
      "Score the fish and rub with oil, salt, and pepper.",
      "Grill on high heat for 4-5 minutes per side until charred and cooked.",
      "Serve with lemon and fresh dill.",
    ],
    createdAt: "2026-04-19",
  }
]

export const dashboardStats = {
  totalRecipes: 1247,
  totalUsers: 8432,
  totalReviews: 15689,
  avgRating: 4.7,
  monthlyVisits: 45200,
  newUsersThisMonth: 342,
}

export const monthlyData = [
  { month: "Sep", recipes: 85, users: 320, views: 12400 },
  { month: "Oct", recipes: 102, users: 380, views: 15600 },
  { month: "Nov", recipes: 95, users: 410, views: 14200 },
  { month: "Dec", recipes: 130, users: 520, views: 21000 },
  { month: "Jan", recipes: 118, users: 480, views: 19800 },
  { month: "Feb", recipes: 145, users: 550, views: 24500 },
]

export const categoryStats = [
  { name: "Pasta", count: 234 },
  { name: "Dessert", count: 198 },
  { name: "Seafood", count: 156 },
  { name: "Bread", count: 142 },
  { name: "Breakfast", count: 189 },
  { name: "Pizza", count: 128 },
  { name: "Salad", count: 98 },
  { name: "Soup", count: 76 },
]

export const recentUsers = [
  { id: "1", name: "Sarah Chen", email: "sarah@example.com", role: "User", recipes: 12, joined: "2026-02-15", status: "Active" },
  { id: "2", name: "Marcus Rodriguez", email: "marcus@example.com", role: "Chef", recipes: 45, joined: "2026-01-20", status: "Active" },
  { id: "3", name: "Emily Watson", email: "emily@example.com", role: "User", recipes: 3, joined: "2026-02-10", status: "Active" },
  { id: "4", name: "James Lee", email: "james@example.com", role: "Admin", recipes: 28, joined: "2025-11-05", status: "Active" },
  { id: "5", name: "Aria Patel", email: "aria@example.com", role: "Chef", recipes: 67, joined: "2025-09-12", status: "Inactive" },
  { id: "6", name: "Lucas Brown", email: "lucas@example.com", role: "User", recipes: 8, joined: "2026-02-18", status: "Active" },
]
